### ISSUE TITLE
"Mojo Retro Adapter NegCon" not detected in Windows 10, II and L buttons not working.

### ISSUE THREAD

**Issue by chaosin2** [rsn8887/RetroAdapterMod#4]
Hi there

I'm using "Normal Firmware v2.1a Mod v1.7"  with my NeGcon attached, but my computer detects "Mojo Retro Adapter" instead of "Mojo Retro Adapter NegCon", all the buttons and twist work fine except II and L.

Hope you can help me, thanks in advance.

**Comment by rsn8887** [comment]
This is happening because Windows 10 does not automatically map the USB HID Axes "Brake" and "Accelerate" to DirectInput axes. Only "Throttle" works.

The solution is to add some lines to the registry.

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\MediaProperties\PrivateProperties\Joystick\OEM\VID_8282&PID_3201\Axes]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\MediaProperties\PrivateProperties\Joystick\OEM\VID_8282&PID_3201\Axes\4]
"Attributes"=hex:00,00,00,00,02,00,c5,00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\MediaProperties\PrivateProperties\Joystick\OEM\VID_8282&PID_3201\Axes\7]
"Attributes"=hex:00,00,00,00,02,00,c4,00
```

Here is the registry file, just unzip and double click the .reg file to add the lines.
[RetroadapterMOD_NegCon_Axes_fix.zip](https://github.com/rsn8887/RetroAdapterMod/files/13445829/RetroadapterMOD_NegCon_Axes_fix.zip)

**Comment by chaosin2** [comment]
Thanks, it works like a charm, you are the man 👍👍👍
